# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: demo.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "CDemoAnimationData",
    "CDemoAnimationHeader",
    "CDemoClassInfo",
    "CDemoClassInfoClassT",
    "CDemoConsoleCmd",
    "CDemoCustomData",
    "CDemoCustomDataCallbacks",
    "CDemoFileHeader",
    "CDemoFileInfo",
    "CDemoFullPacket",
    "CDemoPacket",
    "CDemoRecovery",
    "CDemoRecoveryDemoInitialSpawnGroupEntry",
    "CDemoSaveGame",
    "CDemoSendTables",
    "CDemoSpawnGroups",
    "CDemoStop",
    "CDemoStringTables",
    "CDemoStringTablesItemsT",
    "CDemoStringTablesTableT",
    "CDemoSyncTick",
    "CDemoUserCmd",
    "CGameInfo",
    "CGameInfoCDotaGameInfo",
    "CGameInfoCDotaGameInfoCHeroSelectEvent",
    "CGameInfoCDotaGameInfoCPlayerInfo",
    "CGameInfoCcsGameInfo",
    "EDemoCommands",
)

import builtins
from dataclasses import dataclass

import betterproto2

from nerine.proto.message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class EDemoCommands(betterproto2.Enum):
    DEM_Error = -1

    DEM_Stop = 0

    DEM_FileHeader = 1

    DEM_FileInfo = 2

    DEM_SyncTick = 3

    DEM_SendTables = 4

    DEM_ClassInfo = 5

    DEM_StringTables = 6

    DEM_Packet = 7

    DEM_SignonPacket = 8

    DEM_ConsoleCmd = 9

    DEM_CustomData = 10

    DEM_CustomDataCallbacks = 11

    DEM_UserCmd = 12

    DEM_FullPacket = 13

    DEM_SaveGame = 14

    DEM_SpawnGroups = 15

    DEM_AnimationData = 16

    DEM_AnimationHeader = 17

    DEM_Recovery = 18

    DEM_Max = 19

    DEM_IsCompressed = 64


@dataclass(eq=False, repr=False)
class CDemoAnimationData(betterproto2.Message):
    entity_id: "int" = betterproto2.field(1, betterproto2.TYPE_SINT32)

    start_tick: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    end_tick: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)

    data: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)

    data_checksum: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)


default_message_pool.register_message("", "CDemoAnimationData", CDemoAnimationData)


@dataclass(eq=False, repr=False)
class CDemoAnimationHeader(betterproto2.Message):
    entity_id: "int" = betterproto2.field(1, betterproto2.TYPE_SINT32)

    tick: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    data: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "CDemoAnimationHeader", CDemoAnimationHeader)


@dataclass(eq=False, repr=False)
class CDemoClassInfo(betterproto2.Message):
    classes: "list[CDemoClassInfoClassT]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "CDemoClassInfo", CDemoClassInfo)


@dataclass(eq=False, repr=False)
class CDemoClassInfoClassT(betterproto2.Message):
    class_id: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    network_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    table_name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "", "CDemoClassInfo.class_t", CDemoClassInfoClassT
)


@dataclass(eq=False, repr=False)
class CDemoConsoleCmd(betterproto2.Message):
    cmdstring: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("", "CDemoConsoleCmd", CDemoConsoleCmd)


@dataclass(eq=False, repr=False)
class CDemoCustomData(betterproto2.Message):
    callback_index: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    data: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "CDemoCustomData", CDemoCustomData)


@dataclass(eq=False, repr=False)
class CDemoCustomDataCallbacks(betterproto2.Message):
    save_id: "list[str]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "", "CDemoCustomDataCallbacks", CDemoCustomDataCallbacks
)


@dataclass(eq=False, repr=False)
class CDemoFileHeader(betterproto2.Message):
    demo_file_stamp: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    network_protocol: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    server_name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    client_name: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    map_name: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    game_directory: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    fullpackets_version: "int" = betterproto2.field(7, betterproto2.TYPE_INT32)

    allow_clientside_entities: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)

    allow_clientside_particles: "bool" = betterproto2.field(9, betterproto2.TYPE_BOOL)

    addons: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)

    demo_version_name: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)

    demo_version_guid: "str" = betterproto2.field(12, betterproto2.TYPE_STRING)

    build_num: "int" = betterproto2.field(13, betterproto2.TYPE_INT32)

    game: "str" = betterproto2.field(14, betterproto2.TYPE_STRING)

    server_start_tick: "int" = betterproto2.field(15, betterproto2.TYPE_INT32)


default_message_pool.register_message("", "CDemoFileHeader", CDemoFileHeader)


@dataclass(eq=False, repr=False)
class CDemoFileInfo(betterproto2.Message):
    playback_time: "float" = betterproto2.field(1, betterproto2.TYPE_FLOAT)

    playback_ticks: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    playback_frames: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)

    game_info: "CGameInfo | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "CDemoFileInfo", CDemoFileInfo)


@dataclass(eq=False, repr=False)
class CDemoFullPacket(betterproto2.Message):
    string_table: "CDemoStringTables | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    packet: "CDemoPacket | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "CDemoFullPacket", CDemoFullPacket)


@dataclass(eq=False, repr=False)
class CDemoPacket(betterproto2.Message):
    data: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "CDemoPacket", CDemoPacket)


@dataclass(eq=False, repr=False)
class CDemoRecovery(betterproto2.Message):
    initial_spawn_group: "CDemoRecoveryDemoInitialSpawnGroupEntry | None" = (
        betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    )

    spawn_group_message: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "CDemoRecovery", CDemoRecovery)


@dataclass(eq=False, repr=False)
class CDemoRecoveryDemoInitialSpawnGroupEntry(betterproto2.Message):
    spawngrouphandle: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    was_created: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "",
    "CDemoRecovery.DemoInitialSpawnGroupEntry",
    CDemoRecoveryDemoInitialSpawnGroupEntry,
)


@dataclass(eq=False, repr=False)
class CDemoSaveGame(betterproto2.Message):
    data: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    steam_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)

    signature: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)

    version: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)


default_message_pool.register_message("", "CDemoSaveGame", CDemoSaveGame)


@dataclass(eq=False, repr=False)
class CDemoSendTables(betterproto2.Message):
    data: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "CDemoSendTables", CDemoSendTables)


@dataclass(eq=False, repr=False)
class CDemoSpawnGroups(betterproto2.Message):
    msgs: "list[bytes]" = betterproto2.field(3, betterproto2.TYPE_BYTES, repeated=True)


default_message_pool.register_message("", "CDemoSpawnGroups", CDemoSpawnGroups)


@dataclass(eq=False, repr=False)
class CDemoStop(betterproto2.Message):
    pass


default_message_pool.register_message("", "CDemoStop", CDemoStop)


@dataclass(eq=False, repr=False)
class CDemoStringTables(betterproto2.Message):
    tables: "list[CDemoStringTablesTableT]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "CDemoStringTables", CDemoStringTables)


@dataclass(eq=False, repr=False)
class CDemoStringTablesItemsT(betterproto2.Message):
    str: "builtins.str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    data: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message(
    "", "CDemoStringTables.items_t", CDemoStringTablesItemsT
)


@dataclass(eq=False, repr=False)
class CDemoStringTablesTableT(betterproto2.Message):
    table_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    items: "list[CDemoStringTablesItemsT]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    items_clientside: "list[CDemoStringTablesItemsT]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    table_flags: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "", "CDemoStringTables.table_t", CDemoStringTablesTableT
)


@dataclass(eq=False, repr=False)
class CDemoSyncTick(betterproto2.Message):
    pass


default_message_pool.register_message("", "CDemoSyncTick", CDemoSyncTick)


@dataclass(eq=False, repr=False)
class CDemoUserCmd(betterproto2.Message):
    cmd_number: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    data: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "CDemoUserCmd", CDemoUserCmd)


@dataclass(eq=False, repr=False)
class CGameInfo(betterproto2.Message):
    dota: "CGameInfoCDotaGameInfo | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    cs: "CGameInfoCcsGameInfo | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("", "CGameInfo", CGameInfo)


@dataclass(eq=False, repr=False)
class CGameInfoCcsGameInfo(betterproto2.Message):
    round_start_ticks: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_INT32, repeated=True
    )


default_message_pool.register_message("", "CGameInfo.CCSGameInfo", CGameInfoCcsGameInfo)


@dataclass(eq=False, repr=False)
class CGameInfoCDotaGameInfo(betterproto2.Message):
    match_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    game_mode: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    game_winner: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)

    player_info: "list[CGameInfoCDotaGameInfoCPlayerInfo]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    leagueid: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    picks_bans: "list[CGameInfoCDotaGameInfoCHeroSelectEvent]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )

    radiant_team_id: "int" = betterproto2.field(7, betterproto2.TYPE_UINT32)

    dire_team_id: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)

    radiant_team_tag: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)

    dire_team_tag: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)

    end_time: "int" = betterproto2.field(11, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "", "CGameInfo.CDotaGameInfo", CGameInfoCDotaGameInfo
)


@dataclass(eq=False, repr=False)
class CGameInfoCDotaGameInfoCHeroSelectEvent(betterproto2.Message):
    is_pick: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    team: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    hero_id: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "",
    "CGameInfo.CDotaGameInfo.CHeroSelectEvent",
    CGameInfoCDotaGameInfoCHeroSelectEvent,
)


@dataclass(eq=False, repr=False)
class CGameInfoCDotaGameInfoCPlayerInfo(betterproto2.Message):
    hero_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    player_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    is_fake_client: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    steamid: "int" = betterproto2.field(4, betterproto2.TYPE_UINT64)

    game_team: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "", "CGameInfo.CDotaGameInfo.CPlayerInfo", CGameInfoCDotaGameInfoCPlayerInfo
)
